spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializererializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=notification-service-group
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.protocol=SMTP
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.from=noreply@webedu.com