spring.datasource.username = postgresedu
spring.datasource.password = postgresEDU5432
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres_web_edu
spring.jpa.hibernate.ddl-auto = update
spring.transaction.rollback-on-commit-failure = true
spring.jpa.hibernate.show_sql = false
spring.jpa.hibernate.format_sql = true
spring.jpa.hibernate.use_sql_comments = true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.bootstrap-servers=localhost:9092