server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ORION-VI/EDU-web-project-Module-2
          default-label: main
          searchPaths: config